### ISSUE TITLE
youtube issues

### ISSUE THREAD

**Issue by tbarnavon** [WaterMediaTeam/watermedia#102]
hey im putting youtube urls on my server using waterframes
i get this error
( also for information its random it works sometimes )
```[23:33:21] [ImageFetch-Worker-1/ERROR]: Exception occurred fixing URL
me.srrapero720.watermedia.api.url.fixers.URLFixer$FixingURLException: Failed to fix URL https://www.youtube.com/watch?v=y1lKVzrD5hk
	at me.srrapero720.watermedia.api.url.fixers.YoutubeFixer.patch(YoutubeFixer.java:83) ~[watermedia-2.0.71.jar%23490!/:2.0.71]
	at me.srrapero720.watermedia.api.url.UrlAPI.fixURL(UrlAPI.java:52) ~[watermedia-2.0.71.jar%23490!/:2.0.71]
	at me.srrapero720.watermedia.api.url.UrlAPI.fixURL(UrlAPI.java:30) ~[watermedia-2.0.71.jar%23490!/:2.0.71]
	at me.srrapero720.watermedia.api.image.ImageFetch.run(ImageFetch.java:75) ~[watermedia-2.0.71.jar%23490!/:2.0.71]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "me.lib720.kiulian.downloader.model.videos.VideoInfo.details()" because "videoInfo" is null
	at me.srrapero720.watermedia.api.url.fixers.YoutubeFixer.patch(YoutubeFixer.java:41) ~[watermedia-2.0.71.jar%23490!/:2.0.71]
	... 9 more
[23:33:21] [ImageFetch-Worker-1/ERROR]: An exception occurred while loading image
java.lang.IllegalArgumentException: Invalid URL
	at me.srrapero720.watermedia.api.image.ImageFetch.run(ImageFetch.java:76) ~[watermedia-2.0.71.jar%23490!/:2.0.71]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]```

**Comment by SrRapero720** [comment]
duplicated/related to #90
