### ISSUE TITLE
watermedia works perfectly on macos in 1.20.1 but crashes in 1.19.2. 

### ISSUE THREAD

**Issue by ProGoofster** [WaterMediaTeam/watermedia#87]
I ran the mod by itself in 1.19.2 and 1.20.1 the mod worked as intended in 1.20.1 but crashed as soon as I tried to play a video in 1.19.2. the java version is the same and everything so I dont think its jna breaking vlc. logs and error attached below

![image](https://github.com/WaterMediaTeam/watermedia/assets/59934842/14c57e86-8ef9-4a26-84e0-11a8baa5eaed)

it appears that --high-priority doesn't work on macos vlc
```
[19:35:20] [modloading-worker-0/INFO] [watermedia/Bootstrap]: Preparing 'WATERMeDIA' on 'Forge'
[19:35:20] [modloading-worker-0/INFO] [watermedia/Bootstrap]: WaterMedia version '2.0.63'
[19:35:20] [modloading-worker-0/INFO] [watermedia/Bootstrap]: OS Detected: Mac OS X (aarch64)
[19:35:20] [modloading-worker-0/INFO] [watermedia/Bootstrap]: Starting CacheAPI
[19:35:20] [modloading-worker-0/INFO] [watermedia/CacheAPI]: Mounted on path '/var/folders/1t/3v6qzrv54tv8k82mqy1bdpw80000gp/T/watermedia/cache/pictures'
[19:35:20] [modloading-worker-0/INFO] [watermedia/Bootstrap]: Module CacheAPI loaded successfully
[19:35:20] [modloading-worker-0/INFO] [watermedia/Bootstrap]: Starting PlayerAPI
[19:35:20] [modloading-worker-0/INFO] [watermedia/PlayerAPI]: Binaries are wrapped
[19:35:20] [modloading-worker-0/INFO] [ne.mi.co.ForgeMod/FORGEMOD]: Forge mod loading, version 43.4.0, for MC 1.19.2 with MCP 20220805.130853
[19:35:20] [modloading-worker-0/WARN] [watermedia/PlayerAPI]: VLC binaries extraction skipped. Extracted version match with wrapped version
[19:35:20] [modloading-worker-0/INFO] [watermedia/PlayerAPI]: Processing VideoLAN log files...
[19:35:20] [modloading-worker-0/INFO] [ne.mi.co.MinecraftForge/FORGE]: MinecraftForge v43.4.0 Initialized
[19:35:20] [modloading-worker-0/INFO] [VLCJ/NativeDiscovery]: Searching on '/var/folders/1t/3v6qzrv54tv8k82mqy1bdpw80000gp/T/watermedia/videolan'
[19:35:20] [modloading-worker-0/INFO] [VLCJ/NativeDiscovery]: Searching on subdirectory '/var/folders/1t/3v6qzrv54tv8k82mqy1bdpw80000gp/T/watermedia/videolan/include'
[19:35:20] [modloading-worker-0/INFO] [VLCJ/NativeDiscovery]: Searching on '/Users/temp/Library/Application Support/PrismLauncher/instances/1.19.2/.minecraft'
[19:35:20] [modloading-worker-0/INFO] [VLCJ/NativeDiscovery]: Searching on subdirectory '/Users/temp/Library/Application Support/PrismLauncher/instances/1.19.2/.minecraft/coremods'
[19:35:20] [modloading-worker-0/INFO] [VLCJ/NativeDiscovery]: Searching on '/Applications/VLC.app/Contents/Frameworks'
[19:35:20] [modloading-worker-0/INFO] [VLCJ/NativeDiscovery]: Searching on subdirectory '/Applications/VLC.app/Contents/Frameworks/Sparkle.framework'
[19:35:20] [modloading-worker-0/INFO] [VLCJ/NativeDiscovery]: Searching on subdirectory '/Applications/VLC.app/Contents/Frameworks/Growl.framework'
[19:35:20] [modloading-worker-0/INFO] [VLCJ/NativeDiscovery]: Searching on subdirectory '/Applications/VLC.app/Contents/Frameworks/Breakpad.framework'
[19:35:20] [modloading-worker-0/INFO] [VLCJ/NativeDiscovery]: Searching on '/Applications/VLC.app/Contents/MacOS/lib'
vlc: unknown option or missing mandatory argument `--high-priority'
Try `vlc --help' for more information.
[19:35:22] [modloading-worker-0/ERROR] [watermedia/PlayerAPI]: Failed to load VLC
java.lang.RuntimeException: Failed to get a new native library instance
at me.lib720.caprica.vlcj.factory.MediaPlayerFactory.newLibVlcInstance(MediaPlayerFactory.java:214) ~[watermedia-2.0.63.jar%23144!/:2.0.63] {re:classloading}
at me.lib720.caprica.vlcj.factory.MediaPlayerFactory.<init>(MediaPlayerFactory.java:108) ~[watermedia-2.0.63.jar%23144!/:2.0.63] {re:classloading}
at me.srrapero720.watermedia.api.player.PlayerAPI.registerFactory(PlayerAPI.java:78) ~[watermedia-2.0.63.jar%23144!/:2.0.63] {re:classloading}
at me.srrapero720.watermedia.api.player.PlayerAPI.start(PlayerAPI.java:199) ~[watermedia-2.0.63.jar%23144!/:2.0.63] {re:classloading}
at me.srrapero720.watermedia.WaterMedia.start(WaterMedia.java:72) ~[watermedia-2.0.63.jar%23144!/:2.0.63] {re:classloading}
at me.srrapero720.watermedia.loaders.ForgeLoader.<init>(ForgeLoader.java:44) ~[watermedia-2.0.63.jar%23144!/:2.0.63] {re:classloading}
at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:70) ~[javafmllanguage-1.19.2-43.4.0.jar%23147!/:?] {}
at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:122) ~[fmlcore-1.19.2-43.4.0.jar%23146!/:?] {}
at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?] {}
at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) [?:?] {}
at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?] {}
at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?] {}
at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?] {}
at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?] {}
at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?] {}
[19:35:22] [modloading-worker-0/INFO] [watermedia/Bootstrap]: Module PlayerAPI loaded successfully
[19:35:22] [modloading-worker-0/INFO] [watermedia/Bootstrap]: Starting ImageAPI
[19:35:22] [modloading-worker-0/INFO] [watermedia/ImageAPI]: Loading image resources in a ImageRenderer instance
[19:35:23] [modloading-worker-0/INFO] [watermedia/Bootstrap]: Module ImageAPI loaded successfully
[19:35:23] [modloading-worker-0/INFO] [watermedia/Bootstrap]: Starting UrlAPI
[19:35:23] [modloading-worker-0/INFO] [watermedia/Bootstrap]: Module UrlAPI loaded successfully
[19:35:23] [modloading-worker-0/INFO] [watermedia/Bootstrap]: Starting RenderAPI
[19:35:23] [modloading-worker-0/INFO] [watermedia/Bootstrap]: Module RenderAPI loaded successfully
[19:35:23] [modloading-worker-0/INFO] [watermedia/Bootstrap]: Startup finished
```

[hs_err_pid4528.log](https://github.com/user-attachments/files/15980212/hs_err_pid4528.1.log)

**Comment by SrRapero720** [comment]
i find some odd things on forge so i have to check if was possible ask a fix update

**Comment by SrRapero720** [comment]
this was fixed long time ago.
